Evolution
charm-13/petcafe pull request #20
Opened 2024-11-18 05:48 UTC by charm-13

Implemented evolution capabilities for creatures.

2024-11-18 19:00 UTC, thuang-28 commented on src/api/creatures.py
> +            if status == None:
can be written as "if not status"

2024-11-18 19:00 UTC, thuang-28 commented on src/api/creatures.py
> +                return {"success": False, "error": f"The creature must have maximum stats before evolving."}
For consistency, add creature id to this error message as well

2024-11-19 07:39 UTC, samikshakarimbil commented on APISpec.md
> +    "success": "boolean"
It might help to return what stage the creature was evolved to

2024-11-19 07:41 UTC, samikshakarimbil requested changes
Overall looks good, I agree with Tracy's feedback

2024-11-19 19:38 UTC, samikshakarimbil approved these changes
Looks good to me

2024-11-19 20:34 UTC, thuang-28 approved these changes
yea, looks good to me

2024-11-20 03:35 UTC, merged