Cart rework
charm-13/petcafe pull request #23
Opened 2024-11-28 09:22 UTC by charm-13

carts.py, catalog.py -> shop.py
/shop/catalog: allows users to view the cafe's catalog of available treats
/shop/purchase: allows users to purchase a treat from the cafe

2024-11-28 09:50 UTC, thuang-28 requested changes
looks very nice; the HTTP status codes look appropriate too. APISpec should be updated to reflect the rework

2024-11-28 09:50 UTC, thuang-28 commented on src/api/shop.py
> +                .mappings()
`success` isn't used for anything but checking for existence, so you can probably leave out the `.mappings().fetchone()` entirely

2024-11-28 22:27 UTC, samikshakarimbil approved these changes
LGTM

2024-11-29 23:49 UTC, thuang-28 requested changes

2024-11-29 23:49 UTC, thuang-28 commented on APISpec.md
> +### 1.1. Get Catalog - `shop/catalog/` (GET)
missing `/` at beginning of endpoint URL

2024-11-29 23:49 UTC, thuang-28 commented on APISpec.md
> +  "treak_sku": "string",
typo...

2024-11-30 02:58 UTC, charm-13 commented on APISpec.md
> +  "treak_sku": "string",
lol whoopsies

2024-11-30 03:14 UTC, thuang-28 approved these changes

2024-11-30 07:17 UTC, merged